Repository metal3-io/metal3-docs, pull requests merged in 2019-12, with the labels that each got.

#58 Added Zoom meeting link
  README.md
Labels: approved, lgtm, size/XS

#61 Documents how to safely remove a BareMetalHost from a cluster.
  design/remove-host.md
Labels: approved, lgtm, size/M

#62 Update Jenkins CI commands for integration tests
  ci/nordix-jenkins.md
Labels: approved, lgtm, size/S

#49 Add a Metal kubed banner design
  images/metal3-banner.pdf
Labels: approved, lgtm, size/XS
