Repository metal3-io/metal3-docs, pull requests merged in 2020-06, with the labels that each got.

#96 template: move design details section before implementation details
  design/_template.md
Labels: approved, lgtm, size/S

#97 mark root device hints design as implemented
  design/user-defined-root-device-hints.md
Labels: approved, lgtm, size/XS

#93 add process doc for migrating reviewer permissions to owners files
  processes/reviewer-permissions-migration.md
Labels: approved, lgtm, size/M

#94 add policy for managing reviewers
  processes/managing-reviewers.md
Labels: approved, lgtm, size/M

#95 Re-inspection API proposal
  design/re-introspection-interface.md
Labels: approved, lgtm, size/M

#103 add zaneb and maelk as approvers for this repository
  OWNERS
Labels: approved, lgtm, size/XS

#104 organize designs into component-specific folders
  design/baremetal-operator/annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/baremetal-operator/bios-config.md
  design/baremetal-operator/bmc-address.md
  design/baremetal-operator/how-ironic-works.md
  design/baremetal-operator/implicit-boot-mode.md
  design/baremetal-operator/managing-provisioning-dependencies.md
  design/baremetal-operator/re-introspection-interface.md
  design/baremetal-operator/reboot-interface.md
  design/baremetal-operator/remove-host.md
  design/baremetal-operator/user-defined-root-device-hints.md
  design/baremetal-operator/worker-config-drive.md
  design/community/cncf-sandbox-application.adoc
  design/community/foundation-proposal.md
  design/hardware-classification-controller/expected-hardware-configuration-validation.md
  design/hardware-classification-controller/hwcc_sequence_diagram.png
  design/helm-charts/single-pod-helm-chart.md
  design/ip-address-manager/ip-address-management-for-networkdata.md
Labels: approved, lgtm, size/XS

#106 Change Metal3 community meeting link
  README.md
Labels: approved, lgtm, size/XS
