Repository metal3-io/metal3-docs, pull requests merged in 2020-07, with the labels that each got.

#110 Update pivoting documentation
  docs/move.md
Labels: approved, lgtm, size/M

#119 Update bare-metal style guide
  design/bare-metal-style-guide.md
Labels: approved, lgtm, size/S

#120 describe unmanaged state for hosts
  design/baremetal-operator/unmanaged-state.md
Labels: approved, lgtm, size/L

#109 add owners files for hcc and helm chart designs
  design/hardware-classification-controller/OWNERS
  design/helm-charts/OWNERS
Labels: approved, lgtm, size/XS

#121 design for setting boot mode explicitly
  design/baremetal-operator/explicit-boot-mode.md
  design/baremetal-operator/implicit-boot-mode.md
Labels: approved, lgtm, size/L

#116 Add a Roadmap document
  processes/roadmap.md
Labels: approved, lgtm, size/M

#108 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: approved, lgtm, size/M

#124 update status of several designs
  design/api-design-principles.md
  design/baremetal-operator/explicit-boot-mode.md
  design/baremetal-operator/hardware-status.md
  design/baremetal-operator/implicit-boot-mode.md
  design/baremetal-operator/reboot-interface.md
  design/baremetal-operator/unmanaged-state.md
  design/ip-address-manager/ip-address-management-for-networkdata.md
Labels: approved, lgtm, size/S

#118 Introducing the new CAPM3 Remediation Controller.
  design/capm3-remediation-controller-proposal.md
Labels: approved, lgtm, size/L

#91 📖 Add a Proposal Document for making BMO as part of CAPM3
  design/baremetal-operator/bmo-part-of-capm3.md
Labels: approved, lgtm, size/L

#125 Add dnsServers field to IPAM
  design/ip-address-manager/ip-address-management-for-networkdata.md
Labels: approved, lgtm, size/M

#99 Add ironic authentication proposal
  design/images/ironic_authentication.drawio
  design/images/ironic_authentication_mTLS.png
  design/ironic_authentication.md
Labels: approved, lgtm, size/L

#128 update state of implicit-boot-mode to replaced
  design/baremetal-operator/explicit-boot-mode.md
  design/baremetal-operator/implicit-boot-mode.md
Labels: approved, lgtm, size/S
