Repository metal3-io/metal3-docs, pull requests merged in 2020-05, with the labels that each got.

#85 Update metadata proposal with new fields
  design/metadata-handling.md
Labels: approved, lgtm, size/S

#88 prepare to add markdown linter job
  .gitignore
  README.md
  crs_reference.md
  design/_template.md
  design/annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/api-design-principles.md
  design/bios-config.md
  design/bmc-address.md
  design/expected-hardware-configuration-validation.md
  design/foundation-proposal.md
  design/hardware-status.md
  design/how-ironic-works.md
  design/image-ownership.md
  design/implicit-boot-mode.md
  design/managing-provisioning-dependencies.md
  design/metadata-handling.md
  design/nodes-machines-and-hosts.md
  design/physical-network-api-prototype.md
  design/reboot-interface.md
  design/single-pod-helm-chart.md
  design/use-ironic.md
  design/user-defined-root-device-hints.md
  design/worker-config-drive.md
  docs/prerequisites.md
  hack/gh-md-toc
  hack/markdownlint.sh
  processes/triage.md
Labels: approved, lgtm, size/XXL

#89 stop using generated table of contents
  design/_template.md
  design/annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/api-design-principles.md
  design/bios-config.md
  design/bmc-address.md
  design/expected-hardware-configuration-validation.md
  design/foundation-proposal.md
  design/hardware-status.md
  design/how-ironic-works.md
  design/image-ownership.md
  design/implicit-boot-mode.md
  design/managing-provisioning-dependencies.md
  design/metadata-handling.md
  design/nodes-machines-and-hosts.md
  design/physical-network-api-prototype.md
  design/reboot-interface.md
  design/single-pod-helm-chart.md
  design/use-ironic.md
  design/user-defined-root-device-hints.md
  design/worker-config-drive.md
  hack/gh-md-toc
Labels: approved, lgtm, size/XL

#87 extend the design principle document
  design/api-design-principles.md
Labels: approved, lgtm, size/M

#86 Add a proposal for ip address management
  design/ip-address-management-for-networkdata.md
  design/metadata-handling.md
Labels: approved, lgtm, size/XL
