Repository metal3-io/metal3-docs, pull requests merged in 2020-02, with the labels that each got.

#72 Add relational diagram for CRs
  crs_reference.md
  images/v1a2_crs.drawio
  images/v1a2_crs.png
  images/v1a2_crs.svg
Labels: approved, lgtm, size/S

#48 Add a design doc for a declarative reboot interface
  design/reboot-interface.md
Labels: approved, lgtm, size/L

#55 Start documenting a set of API design principles
  design/api-design-principles.md
Labels: approved, lgtm, size/M

#75 do not assume machine API in designs
  design/api-design-principles.md
Labels: approved, lgtm, size/XS

#74 Prerequisites for running metal3 components to run on vanilla K8s cluster
  docs/prerequisites.md
Labels: approved, lgtm, size/M
