Repository metal3-io/metal3-docs, pull requests merged in 2020-09, with the labels that each got.

#131 Add Metal3 architectural diagrams
  images/architectural diagrams/cluster_api.svg
  images/architectural diagrams/components.svg
  images/architectural diagrams/ipam.svg
  images/architectural diagrams/object_representation.svg
Labels: approved, lgtm, size/S

#135 Add list of OWNERS across all repositories
  maintainers/ALL-OWNERS
  maintainers/README.md
  maintainers/all-owners.sh
Labels: approved, lgtm, size/M

#123 describe baremetal-operator migration to kubebuilder
  design/baremetal-operator/kubebuilder-migration.md
Labels: approved, lgtm, size/L
