Repository metal3-io/metal3-docs, pull requests merged in 2020-01, with the labels that each got.

#57 Propose a process for adding/removing maintainers
  maintainers/README.md
Labels: approved, lgtm, size/L

#65 Update nordix ci description to match the commands
  ci/nordix-jenkins.md
Labels: approved, lgtm, size/S

#59 Create annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/annotation-for-power-cycling-and-deleting-failed-nodes.md
Labels: approved, lgtm, size/L

#67 Remove jenkins docs (moved to project-infra)
  ci/nordix-jenkins.md
Labels: approved, lgtm, size/M

#68 Add metal3-dev-env high level architecture image
  images/metal3-dev-env-transparent.png
  images/metal3-dev-env.png
  images/metal3-dev-env.svg
Labels: approved, lgtm, size/XS

#70 Fix networking mismatch in dev-env image
  images/metal3-dev-env-transparent.png
  images/metal3-dev-env.png
  images/metal3-dev-env.svg
Labels: approved, lgtm, size/XS
