Repository metal3-io/metal3-docs, pull requests merged in 2020-03, with the labels that each got.

#69 Triage proccess proposal
  processes/triage.md
Labels: approved, lgtm, size/M

#81 Update community meeting's zoom link
  README.md
Labels: approved, lgtm, size/XS

#77 Propose applying to the CNCF Sandbox
  design/foundation-proposal.md
Labels: approved, lgtm, size/L

#78 design for determining the boot mode from other data
  design/implicit-boot-mode.md
Labels: approved, lgtm, size/L
