Repository metal3-io/metal3-docs, pull requests merged in 2021-10, with the labels that each got.

#199 Adopters: add Airship
  ADOPTERS.md
Labels: size/XS, approved, lgtm, ok-to-test

#200 Add Das SCHIFF to adopters
  ADOPTERS.md
Labels: size/XS, approved, lgtm, ok-to-test

#196 Hardware RAID Extension - Physical disks and RAID controller
  design/baremetal-operator/bios-config.md
  design/baremetal-operator/raid-disk-controller.md
Labels: size/L, approved, lgtm, ok-to-test

#203 Update project maintainers list
  maintainers/ALL-OWNERS
  maintainers/all-owners.sh
Labels: approved, size/S, lgtm
