Repository metal3-io/metal3-docs, pull requests merged in 2021-06, with the labels that each got.

#183 Propose deploy ramdisk Image build API and integration
  design/baremetal-operator/image-builder-integration.md
Labels: approved, lgtm, size/L

#178 Design: propose reproducible metal3-dev-env
  design/reproducible-metal3-dev-env.md
Labels: approved, lgtm, size/L

#184 Fix a typo in the custom deploy design
  design/deploy-steps.md
Labels: approved, lgtm, size/XS

#165 Update Remediation Controller proposal
  design/capm3-remediation-controller-proposal.md
Labels: approved, lgtm, size/M
