Repository metal3-io/metal3-docs, pull requests merged in 2021-04, with the labels that each got.

#169 Add update strategy to Metal3DataTemplate
  design/metadata-handling.md
Labels: approved, lgtm, size/M

#174 Update inspection API proposal status
  design/baremetal-operator/inspection-api.md
Labels: approved, lgtm, size/XS

#163 Presentations framework proposal with a sample presentation
  docs/presentations/README.md
  docs/presentations/metal3-overview/metal3-components.png
  docs/presentations/metal3-overview/metal3-integration-capi.png
  docs/presentations/metal3-overview/metal3-overview.html
  docs/presentations/metal3-overview/slide-example-1.png
  docs/presentations/metal3-overview/slide-example-2.png
  docs/presentations/metal3-overview/slide-example-3.png
Labels: size/L
