Repository metal3-io/metal3-docs, pull requests merged in 2021-02, with the labels that each got.

#138 design: add sub-states
  design/baremetal-operator/sub-states.md
Labels: approved, lgtm, size/L

#161 design: support automatic secure boot
  design/baremetal-operator/secure-boot.md
Labels: approved, lgtm, size/L

#149 Add design proposal for label sync mechanism between BMHs and K Nodes
  design/sync-labels-bmh-to-node.md
Labels: approved, lgtm, ok-to-test, size/L

#164 Add explicit reboot mode options
  design/baremetal-operator/reboot-interface.md
Labels: approved, lgtm, ok-to-test, size/S
