Repository metal3-io/metal3-docs, pull requests merged in 2021-01, with the labels that each got.

#157 Fix typo
  design/baremetal-operator/user-defined-root-device-hints.md
Labels: approved, lgtm, ok-to-test, size/XS

#122 Update Metal3-dev-env images
  images/metal3-dev-env-transparent.png
  images/metal3-dev-env.png
  images/metal3-dev-env.svg
Labels: approved, lgtm, lifecycle/stale, size/XS

#153 Update README
  README.md
  hack/markdownlint.sh
Labels: approved, lgtm, size/M

#154 Add user-guide structure & tooling
  .gitignore
  Makefile
  docs/instructions.md
  docs/user-guide/book.toml
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/images/metal3-color.svg
  docs/user-guide/src/introduction.md
  docs/user-guide/theme/favicon.svg
Labels: approved, lgtm, size/L

#158 Add Dockerfile for mdbook
  Makefile
  docs/Dockerfile
  docs/instructions.md
  netlify.toml
Labels: approved, lgtm, size/L

#159 Update community meeting occurrence
  README.md
Labels: approved, lgtm, size/XS

#150 Add BMH live-iso proposal
  design/baremetal-operator/bmh_live_iso.md
Labels: approved, lgtm, size/L
