Repository metal3-io/metal3-docs, pull requests merged in 2021-03, with the labels that each got.

#152 Proposal for new parameters: Disk and NIC in HWCC
  design/hardware-classification-controller/support-for-new-parameters-hwcc-DiskAndNIC.md
Labels: approved, lgtm, ok-to-test, size/L

#147 Support for new parameters in HWCC.
  design/hardware-classification-controller/support-for-new-parameters-hwcc.md
Labels: approved, lgtm, ok-to-test, size/L

#162 ✨ Proposal: node reuse
  design/cluster-api-provider-metal3/node_reuse.md
  design/images/node_reuse_flow.svg
Labels: approved, lgtm, size/L

#166 Update disabling automated cleaning proposal
  design/cluster-api-provider-metal3/allow_disabling_node_disk_cleaning.md
Labels: approved, lgtm, size/M

#155 Add proposal for supporting external introspection
  design/baremetal-operator/external-introspection.md
Labels: approved, lgtm, size/L

#172 add feruzjon muyassarov as approver
  OWNERS
Labels: approved, lgtm, size/XS
