Repository metal3-io/metal3-docs, pull requests merged in 2022-04, with the labels that each got.

#246 📖 User guide: Add nodeReuse feature document
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/capm3/node_reuse.md
Labels: approved, lgtm, size/M

#247 :book: Add IPAM introduction document
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/ipam/ipam.md
Labels: approved, lgtm, size/M

#242 User-guide: Add automated cleaning feature user document
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/automated_cleaning.md
  docs/user-guide/src/capm3/automated_cleaning.md
  docs/user-guide/src/capm3/images/object-ref.plantuml
  docs/user-guide/src/capm3/images/object-ref.svg
Labels: size/L, approved, lgtm

#260 User-guide: add user-guide URL
  README.md
  docs/user-guide/README.md
Labels: size/XS, approved, lgtm
