Repository metal3-io/metal3-docs, pull requests merged in 2022-06, with the labels that each got.

#263 📖 User-guide: Add detached and status annotation docs
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/detached_annotation.md
  docs/user-guide/src/bmo/status_annotation.md
Labels: size/L, approved, lgtm

#262 📖 Add docs for BMO reboot annotation
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/reboot_annotation.md
Labels: approved, lgtm, size/M

#266 🐛 Fix mailing list reference in the README
  README.md
Labels: size/XS, approved, lgtm

#211 Presentation revealjs update
  .gitignore
  docs/presentations/README.md
Labels: approved, lgtm, size/M

#257 Add Ironic introduction
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/ironic/introduction.md
Labels: approved, lgtm, size/M
