Repository metal3-io/metal3-docs, pull requests merged in 2022-07, with the labels that each got.

#265 📖 Update release version notes in user guide
  docs/user-guide/src/capm3/installation_guide.md
  docs/user-guide/src/version_support.md
Labels: approved, size/S, lgtm

#269 [trivial] Fix typo in ironic python agent name
  docs/user-guide/src/ironic/ironic-python-agent.md
Labels: size/XS, approved, lgtm

#264 Update hardwareData proposal status
  design/baremetal-operator/hardwaredata_crd.md
Labels: approved, lgtm, size/M

#252 User-guide: Add Ironic installation in Metal3
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/ironic_bmo_configmap.env
  docs/user-guide/src/ironic/ironic_installation.md
  docs/user-guide/src/ironic/ironic_variables.md
Labels: size/L, approved, lgtm
