Repository metal3-io/metal3-docs, pull requests merged in 2022-11, with the labels that each got.

#277 User guide: explain Node deletion for reboot remediation strategy
  docs/user-guide/src/capm3/remediaton.md
Labels: size/XS, approved, lgtm, ok-to-test

#287 📖 Update version support notes
  docs/user-guide/src/version_support.md
Labels: approved, lgtm, size/M

#284 User-guide: Add BMO live-iso
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/live-iso.md
Labels: approved, lgtm, size/M

#291 Update unified OWNERS file for user-guide patches
  docs/user-guide/src/OWNERS
Labels: approved, size/S, lgtm

#282 Add automatic secure boot docs
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/automatic_secure_boot.md
Labels: approved, lgtm, size/M

#292 remove inactive reviewer from user-guide reviewers
  docs/user-guide/src/OWNERS
Labels: size/XS, approved, lgtm

#280 Add CAPM3 Introduction doc
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/capm3/introduction.md
Labels: approved, do-not-merge/hold, lgtm, size/M

#293 Introduce general security policy for Metal3-io
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/security_policy.md
Labels: size/L, approved, lgtm

#294 :book: Fix smaller nits in user-guide
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/capm3/introduction.md
Labels: size/XS, approved, lgtm

#270 Add how to build ironic images section
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/ironic/ironic-container-images.md
Labels: approved, lgtm, size/M

#295 Add section about inspection
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/inspect_annotation.md
Labels: approved, lgtm, size/M

#296 add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, size/S, lgtm

#297 Add build arg options section for custom source build of ironic-image
  docs/user-guide/src/ironic/ironic-container-images.md
Labels: approved, size/S, lgtm
