Repository metal3-io/metal3-docs, pull requests merged in 2022-02, with the labels that each got.

#239 Correct comunity meeting time information
  README.md
Labels: size/XS, approved, lgtm

#241 remove Jan as an active reviewer
  docs/user-guide/src/capm3/OWNERS
Labels: size/XS, approved, lgtm

#208 HostData CR for host inspection data
  design/baremetal-operator/hostdata_crd.md
Labels: size/L, approved, lgtm

#245 Fix mdbook quay image tag and bump mdBook version
  Makefile
  docs/Dockerfile
  docs/README.md
  docs/user-guide/README.md
Labels: approved, lgtm, size/M

#244 Update introduction based on feedback
  docs/user-guide/src/introduction.md
Labels: approved, size/S, lgtm
