Repository metal3-io/metal3-docs, pull requests merged in 2022-01, with the labels that each got.

#212 Replace master branch reference with main
  README.md
  design/baremetal-operator/bmo-part-of-capm3.md
  design/baremetal-operator/detached-annotation.md
  design/baremetal-operator/external-introspection.md
  design/baremetal-operator/implicit-boot-mode.md
  design/baremetal-operator/inspection-api.md
  design/baremetal-operator/managing-provisioning-dependencies.md
  design/baremetal-operator/reboot-interface.md
  design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
  design/cluster-api-provider-metal3/node_reuse.md
  design/community/cncf-sandbox-application.adoc
  design/hardware-classification-controller/expected-hardware-configuration-validation.md
  design/ip-address-manager/ip-address-management-for-networkdata.md
  design/ironic-debuggability-improvement.md
  design/ironic_authentication.md
  design/reproducible-metal3-dev-env.md
  docs/presentations/metal3-overview/metal3-overview.html
  maintainers/all-owners.sh
Labels: approved, lgtm, size/M

#213 Add initial skeleton for the user-guide
  docs/user-guide/README.md
  docs/user-guide/book.toml
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/OWNERS
  docs/user-guide/src/capm3/OWNERS
  docs/user-guide/src/ipam/OWNERS
  docs/user-guide/src/ironic/OWNERS
  hack/markdownlint.sh
Labels: size/L, approved, lgtm

#235 move maelk to emeritus_approvers list
  OWNERS
Labels: size/XS, approved, lgtm

#238 change subdirectory ownership
  docs/user-guide/src/bmo/OWNERS
  docs/user-guide/src/capm3/OWNERS
  docs/user-guide/src/ipam/OWNERS
  docs/user-guide/src/ironic/OWNERS
  maintainers/ALL-OWNERS
Labels: approved, size/S, lgtm

#236 Add User Guide Metal3 intro
  docs/user-guide/src/introduction.md
Labels: approved, lgtm, size/M
