Repository metal3-io/metal3-docs, pull requests merged in 2023-11, with the labels that each got.

#345 BMO CI Decoupling proposal
  design/baremetal-operator/bmo-ci-decoupling.md
Labels: approved, lgtm, size/M

#366 Update the maintainers list
  maintainers/ALL-OWNERS
Labels: approved, size/S, lgtm

#367 fix and simplify all-owners script
  maintainers/all-owners.sh
Labels: approved, lgtm, size/M

#368 Update the ALL-OWNERS file with up to date maintainer list
  maintainers/ALL-OWNERS
Labels: size/XS, approved, lgtm
