Repository metal3-io/metal3-docs, pull requests merged in 2023-05, with the labels that each got.

#327 Fix Ironic installation link
  docs/user-guide/src/capm3/installation_guide.md
Labels: size/XS, approved, lgtm, ok-to-test

#331 pin rust:1-slim as rust:1.69.0-slim
  docs/Dockerfile
Labels: size/XS, approved, lgtm

#321 add releasing.md
  processes/releasing.md
Labels: size/L, approved, lgtm

#333 Broken links fix in design folder
  design/_template.md
  design/community/foundation-proposal.md
Labels: size/XS, approved, lgtm, ok-to-test
