Repository metal3-io/metal3-docs, pull requests merged in 2023-03, with the labels that each got.

#276 Proposal: add node deletion in remediation controller (implemented)
  design/cluster-api-provider-metal3/capm3-remediation-controller-improvement-proposal.md
Labels: size/L, approved, lgtm, ok-to-test

#289 User-guide: Add ironic dnsmasq DNS & GW IP environment
  docs/user-guide/src/ironic/ironic_variables.md
Labels: size/XS, approved, lgtm, ok-to-test

#312 Proof-read user guide: ironic/introduction
  docs/user-guide/src/ironic/introduction.md
Labels: approved, lgtm, size/M

#311 update default RDO OS from Centos8 to Centos9
  docs/user-guide/src/ironic/ironic-python-agent.md
Labels: size/XS, approved, lgtm

#310 update repositories and ALL-OWNERS
  maintainers/ALL-OWNERS
  maintainers/all-owners.sh
Labels: size/XS, approved, lgtm

#317 Add Kashif and Adam as reviewers to /design OWNERS file
  design/OWNERS
Labels: size/XS, approved, lgtm
