Repository metal3-io/metal3-docs, pull requests merged in 2023-08, with the labels that each got.

#341 Update OWNERS of user-guide
  docs/user-guide/src/OWNERS
Labels: size/XS, approved, lgtm

#340 Setup section for dev-env
  docs/user-guide/src/developer_environment/tryit.md
Labels: approved, lgtm, ok-to-test, size/M

#342 Working with environment section
  docs/user-guide/src/developer_environment/tryit.md
Labels: approved, size/XL, lgtm, ok-to-test

#347 Make baremetal installation guide more prominent
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/baremetal/guide.md
Labels: size/XS, approved, lgtm
