Repository metal3-io/metal3-docs, pull requests merged in 2023-09, with the labels that each got.

#349 Update versioning doc for release-1.5
  docs/user-guide/src/version_support.md
Labels: size/L, approved, lgtm

#352 Add page Install Baremetal Operator
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/install_baremetal_operator.md
Labels: size/L, approved, lgtm, ok-to-test

#353 update releasing.md
  processes/releasing.md
Labels: approved, lgtm, size/M

#355 Add new adopter
  ADOPTERS.md
Labels: size/XS, approved, lgtm, ok-to-test

#357 update version_support.md
  docs/user-guide/src/version_support.md
Labels: approved, lgtm, size/M
