Repository metal3-io/metal3-docs, pull requests merged in 2023-10, with the labels that each got.

#346 Update Ironic installation guide
  docs/user-guide/src/ironic/ironic_installation.md
Labels: approved, lgtm, size/M

#359 add tuminoid to reviewers
  OWNERS
Labels: size/XS, approved, lgtm

#358 Fix quick start link in README
  README.md
Labels: size/XS, approved, lgtm

#344 Updates to try-it page
  docs/user-guide/src/developer_environment/tryit.md
Labels: approved, size/S, lgtm, ok-to-test

#360 Update the root and design OWNERS
  OWNERS
  design/OWNERS
Labels: approved, size/S, lgtm

#332 BareMetalHost API v1beta1
  design/baremetal-operator/bmh-v1beta1.md
Labels: size/L, approved, lgtm

#363 Add SUSE to ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test

#361 Add BMO release-0.4 and release-0.3 branch in version support guide
  docs/user-guide/src/version_support.md
Labels: approved, size/S, lgtm
