Repository metal3-io/metal3-docs, pull requests merged in 2023-12, with the labels that each got.

#371 fix Furkat's employment
  docs/user-guide/src/security_policy.md
Labels: size/XS, approved, lgtm

#370 Remove duplicate files which reside in community/ repo
  ADOPTERS.md
  design/community/foundation-proposal.md
  maintainers/ALL-OWNERS
  maintainers/README.md
  maintainers/all-owners.sh
  processes/managing-reviewers.md
Labels: size/L, approved, lgtm

#372 add clomonitor badge to README
  README.md
Labels: size/XS, approved, lgtm

#374 remove outdated CoC and link the new one
  CODE_OF_CONDUCT.md
  README.md
Labels: approved, lgtm, size/M
