Repository metal3-io/metal3-docs, pull requests merged in 2024-05, with the labels that each got.

#421 Bump rust to v0.4.37
  Makefile
  netlify.toml
Labels: size/XS, approved, lgtm

#419 hack/tools: reduce required Go version
  hack/tools/go.mod
Labels: size/XS, approved, lgtm

#418 User guide: completely rework the BMO introduction
  docs/user-guide/src/bmo/images/ipa-inspection.plantuml
  docs/user-guide/src/bmo/images/ipa-inspection.png
  docs/user-guide/src/bmo/images/ipa-provisioning.plantuml
  docs/user-guide/src/bmo/images/ipa-provisioning.png
  docs/user-guide/src/bmo/introduction.md
Labels: size/L, approved, lgtm

#414 Add baremetal-operator image version in kustomization.yaml example
  docs/user-guide/src/quick-start.md
Labels: size/XS, approved, lgtm, ok-to-test

#426 🌱 Move furkatgofurov7 to emeritus approvers
  OWNERS
  design/OWNERS
  docs/user-guide/src/security_policy.md
Labels: size/XS, approved, lgtm

#427 User guide: expand Ironic introduction
  docs/user-guide/src/ironic/introduction.md
Labels: size/L, approved, lgtm

#430 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
  design/OWNERS
Labels: approved, lgtm, size/M

#428 User guide: migrate BMC addressing information from BMO
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/baremetal/guide.md
  docs/user-guide/src/bmo/introduction.md
  docs/user-guide/src/bmo/supported_hardware.md
  docs/user-guide/src/quick-start.md
Labels: size/L, approved, lgtm

#431 User guide: update information on Ironic container images
  docs/user-guide/src/ironic/ironic-container-images.md
Labels: approved, lgtm, size/M

#425 Add docker-build target
  .gitignore
  Makefile
  docs/Dockerfile
Labels: approved, lgtm, size/M

#432 User guide: clean-up the BMO features
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/automated_cleaning.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/inspect_annotation.md
  docs/user-guide/src/bmo/live-iso.md
  docs/user-guide/src/bmo/reboot_annotation.md
Labels: size/L, approved, lgtm

#434 Add project overview page
  .gitignore
  Makefile
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/images/capi-machines.pantuml
  docs/user-guide/src/images/capi-machines.png
  docs/user-guide/src/images/metal3-capi-objects.plantuml
  docs/user-guide/src/images/metal3-capi-objects.png
  docs/user-guide/src/images/metal3-stack.plantuml
  docs/user-guide/src/images/metal3-stack.png
  docs/user-guide/src/project-overview.md
Labels: size/L, approved, lgtm

#433 fix broken link to a kubelet kep
  design/sync-labels-bmh-to-node.md
Labels: size/XS, approved, lgtm
