Repository metal3-io/metal3-docs, pull requests merged in 2024-08, with the labels that each got.

#454 Fixed dead link
  design/baremetal-operator/kubebuilder-migration.md
Labels: size/XS, approved, lgtm, ok-to-test

#462 Update Metal3 Remediation section
  docs/user-guide/src/capm3/remediaton.md
Labels: size/XS, approved, lgtm, ok-to-test

#459 Add support for UEFI HTTP boot
  design/baremetal-operator/uefi-http-boot.md
Labels: size/L, approved, lgtm

#466 User guide: document basic provisioning and deprovisioning
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/provisioning.md
Labels: size/L, approved, lgtm

#463 :seedling: Add release 1.8 to the test matrix
  docs/user-guide/src/version_support.md
Labels: approved, lgtm, size/M
