Repository metal3-io/metal3-docs, pull requests merged in 2024-04, with the labels that each got.

#407 :book: Fix ironic installation with kustomize instruction
  docs/user-guide/src/ironic/ironic_installation.md
Labels: approved, lgtm, size/M

#409 :book: Fix book markdown url issue
  docs/user-guide/src/ironic/ironic_installation.md
Labels: approved, size/S, lgtm

#410 Remove extra OWNERS files and propose more reviewers in root OWNERS
  OWNERS
  design/hardware-classification-controller/OWNERS
  design/helm-charts/OWNERS
  docs/user-guide/src/OWNERS
Labels: approved, lgtm, size/M

#392 Add ironic image version in kustomization.yaml example
  docs/user-guide/src/quick-start.md
Labels: size/XS, approved, lgtm, ok-to-test

#406 CRDs and godoc reference for main projects
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/reference/bmo.md
  docs/user-guide/src/reference/capm3.md
  docs/user-guide/src/reference/ipam.md
Labels: approved, size/S, lgtm, ok-to-test

#415 Fix virtualized environment
  docs/user-guide/src/quick-start.md
Labels: size/XS, approved, lgtm, ok-to-test
