Repository metal3-io/metal3-docs, pull requests merged in 2024-09, with the labels that each got.

#469 :seedling: Add ironic release-26.0 to the version support
  docs/user-guide/src/version_support.md
Labels: approved, size/S, lgtm

#467 :seedling: Remove release 1.5 from test matrix
  docs/user-guide/src/version_support.md
Labels: approved, lgtm, size/M

#470 Quick start: pass HTTP_PORT to dnsmasq.env
  docs/user-guide/src/quick-start.md
Labels: size/XS, approved, lgtm

#471 Add white background to ipa-provisioning.png
  docs/user-guide/src/bmo/images/ipa-provisioning.png
Labels: size/XS, approved, lgtm

#472 Add label sync documentation to book
  docs/user-guide/src/capm3/features.md
  docs/user-guide/src/capm3/label_sync.md
Labels: approved, lgtm, size/M
