Repository metal3-io/metal3-docs, pull requests merged in 2024-11, with the labels that each got.

#483 user-guide: Add Pre-Provisioning NetworkData details
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/advanced_instance_customization.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/instance_customization.md
Labels: approved, lgtm, size/M

#484 User guide: troubleshooting: describe the issue with forced deletion
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/troubleshooting.md
Labels: approved, lgtm, size/M

#456 add security self-assessment document
  security/self-assessment.md
Labels: size/L, approved, lgtm

#487 Add v27.0 supported ironic-image
  docs/user-guide/src/version_support.md
Labels: size/XS, approved, lgtm

#485 Add live updates documentation
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/firmware_settings.md
  docs/user-guide/src/bmo/firmware_updates.md
  docs/user-guide/src/bmo/live_updates_servicing.md
Labels: size/L, approved, lgtm
