Repository metal3-io/metal3-docs, pull requests merged in 2024-06, with the labels that each got.

#424 :seedling: Add warning about links without a path
  docs/user-guide/src/SUMMARY.md
Labels: size/XS, approved, lgtm

#436 shellcheck only files
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm

#411 Live updates (servicing) for hosts
  design/baremetal-operator/host-live-updates.md
Labels: size/L, approved, lgtm

#438 update version support tables
  docs/user-guide/src/version_support.md
Labels: approved, size/S, lgtm

#437 User guide: document firmware settings
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/firmware_settings.md
Labels: size/L, approved, lgtm

#451 add elfosardo to reviewers group
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#452 Fix dead links at cap3-remidiation-controller.md
  design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
Labels: size/XS, approved, lgtm, ok-to-test

#450 User guide: information on instance customization
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/instance_customization.md
  docs/user-guide/src/quick-start.md
Labels: size/L, approved, lgtm
