Repository metal3-io/metal3-docs, pull requests merged in 2024-03, with the labels that each got.

#384 Quick start for Metal3
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/quick-start.md
Labels: approved, size/XL, lgtm

#391 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm

#393 Fix the Getting Started Guide link in introduction to try it section
  docs/user-guide/src/introduction.md
Labels: size/XS, approved, lgtm, ok-to-test

#382 User guide: updates for Inspector removal
  docs/user-guide/src/baremetal/guide.md
  docs/user-guide/src/bmo/install_baremetal_operator.md
  docs/user-guide/src/bmo/ironic_bmo_configmap.env
  docs/user-guide/src/capm3/pivoting.md
  docs/user-guide/src/developer_environment/tryit.md
  docs/user-guide/src/ironic/ironic-python-agent.md
  docs/user-guide/src/ironic/ironic_installation.md
  docs/user-guide/src/ironic/ironic_variables.md
Labels: approved, lgtm, size/M

#390 In quick-start, update all references to use Bare Metal Operator v0.5.1
  docs/user-guide/src/quick-start.md
Labels: approved, size/S, lgtm, ok-to-test

#380 Update on howto manually set nested-virtualization
  docs/user-guide/src/developer_environment/tryit.md
Labels: approved, size/S, lgtm, ok-to-test

#404 Typo in authentication config section
  docs/user-guide/src/quick-start.md
Labels: size/XS, approved, lgtm, ok-to-test

#405 update releasing doc
  processes/releasing.md
Labels: approved, size/S, lgtm
