Repository metal3-io/metal3-docs, pull requests merged in 2024-10, with the labels that each got.

#464 Add documentation for Firmware Updates to Metal3 Book
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/firmware_updates.md
Labels: size/L, approved, lgtm

#476 bump markdownlint-cli2 to v0.12.0
  hack/markdownlint.sh
Labels: size/XS, approved, lgtm

#474 update cspell spellchecker to v8.13.3
  hack/spellcheck.sh
Labels: size/XS, approved, lgtm

#473 User guide: expand the detached annotation page
  docs/user-guide/src/bmo/detached_annotation.md
Labels: approved, size/S, lgtm

#461 Ironic Standalone Operator
  .cspell-config.json
  design/ironic-standalone-operator.md
Labels: size/L, approved, lgtm

#385 Added info on ClusterClass use
  docs/user-guide/src/capm3/clusterclass.md
Labels: approved, lgtm, ok-to-test, size/M

#480 fix spellcheck glob and spellcheck issues that follow
  .cspell-config.json
  README.md
  design/baremetal-operator/annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/baremetal-operator/bmc-events.md
  design/baremetal-operator/bmh_live_iso.md
  design/baremetal-operator/bmh_non-bootable_iso.md
  design/baremetal-operator/bmo-ci-decoupling.md
  design/baremetal-operator/bmo-part-of-capm3.md
  design/baremetal-operator/bulk-set-bios-config.md
  design/baremetal-operator/deploy-steps.md
  design/baremetal-operator/detached-annotation.md
  design/baremetal-operator/hardware-status.md
  design/baremetal-operator/hardwaredata_crd.md
  design/baremetal-operator/host-config-drive.md
  design/baremetal-operator/how-ironic-works.md
  design/baremetal-operator/image-builder-integration.md
  design/baremetal-operator/inspection-api.md
  design/baremetal-operator/kubebuilder-migration.md
  design/baremetal-operator/managing-provisioning-dependencies.md
  design/baremetal-operator/raid-disk-controller.md
  design/baremetal-operator/reboot-interface.md
  design/baremetal-operator/remove-host.md
  design/baremetal-operator/uefi-http-boot.md
  design/baremetal-operator/user-defined-root-device-hints.md
  design/cluster-api-provider-metal3/allow_disabling_node_disk_cleaning.md
  design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
  design/cluster-api-provider-metal3/node_reuse.md
  design/community/book-proposal.md
  design/community/foundation-proposal.md
  design/hardware-classification-controller/expected-hardware-configuration-validation.md
  design/hardware-classification-controller/support-for-error-count-parameter-hwcc.md
  design/hardware-classification-controller/support-for-new-parameters-hwcc-DiskAndNIC.md
  design/helm-charts/single-pod-helm-chart.md
  design/ip-address-manager/ip-address-management-for-networkdata.md
  docs/presentations/README.md
  docs/user-guide/src/baremetal/guide.md
  docs/user-guide/src/bmo/firmware_settings.md
  docs/user-guide/src/bmo/install_baremetal_operator.md
  docs/user-guide/src/bmo/instance_customization.md
  docs/user-guide/src/bmo/introduction.md
  docs/user-guide/src/bmo/provisioning.md
  docs/user-guide/src/bmo/raid.md
  docs/user-guide/src/bmo/root_device_hints.md
  docs/user-guide/src/bmo/state_machine.md
  docs/user-guide/src/capm3/automated_cleaning.md
  docs/user-guide/src/capm3/clusterclass.md
  docs/user-guide/src/capm3/installation_guide.md
  docs/user-guide/src/capm3/label_sync.md
  docs/user-guide/src/capm3/pivoting.md
  docs/user-guide/src/developer_environment/tryit.md
  docs/user-guide/src/introduction.md
  docs/user-guide/src/ipam/ipam_installation.md
  docs/user-guide/src/ironic/introduction.md
  docs/user-guide/src/ironic/ironic-container-images.md
  docs/user-guide/src/ironic/ironic_installation.md
  docs/user-guide/src/project-overview.md
  docs/user-guide/src/quick-start.md
  docs/user-guide/src/security_policy.md
  docs/user-guide/src/version_support.md
  hack/spellcheck.sh
Labels: size/L, approved, lgtm

#481 User guide: fix missing checksumType in samples
  docs/user-guide/src/bmo/instance_customization.md
  docs/user-guide/src/bmo/provisioning.md
Labels: approved, size/S, lgtm

#482 fix some more spelling issues
  .cspell-config.json
  design/baremetal-operator/bmc-events.md
  design/baremetal-operator/how-ironic-works.md
  design/baremetal-operator/image-builder-integration.md
  design/baremetal-operator/reboot-interface.md
  design/baremetal-operator/user-defined-root-device-hints.md
Labels: approved, size/S, lgtm

#478 Design: hardware that cannot be powered off
  design/baremetal-operator/disable-power-off.md
Labels: size/L, approved, lgtm
