Repository metal3-io/metal3-docs, pull requests merged in 2024-01, with the labels that each got.

#375 update releasing.md
  processes/releasing.md
Labels: approved, lgtm, size/M

#376 Add release-1.6 to the testing matrix
  docs/user-guide/src/version_support.md
Labels: approved, lgtm, size/M

#377 Improvements and fixes in baremetal guide
  docs/user-guide/src/baremetal/guide.md
Labels: approved, lgtm, size/M

#378 switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  README.md
  design/baremetal-operator/annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/baremetal-operator/bmh-v1beta1.md
  design/baremetal-operator/hardware-status.md
  design/baremetal-operator/hardwaredata_crd.md
  design/baremetal-operator/how-ironic-works.md
  design/baremetal-operator/kubebuilder-migration.md
  design/baremetal-operator/raid-disk-controller.md
  design/baremetal-operator/sub-states.md
  design/cluster-api-provider-metal3/allow_disabling_node_disk_cleaning.md
  design/cluster-api-provider-metal3/node_reuse.md
  design/fd-support-kcp.md
  design/hardware-classification-controller/expected-hardware-configuration-validation.md
  design/hardware-classification-controller/support-for-error-count-parameter-hwcc.md
  design/helm-charts/single-pod-helm-chart.md
  design/ip-address-manager/ip-address-management-for-networkdata.md
  design/ironic-debuggability-improvement.md
  design/metadata-handling.md
  design/physical-network-api-prototype.md
  design/sync-labels-bmh-to-node.md
  docs/README.md
  docs/prerequisites.md
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/baremetal/guide.md
  docs/user-guide/src/bmo/automated_cleaning.md
  docs/user-guide/src/bmo/introduction.md
  docs/user-guide/src/bmo/live-iso.md
  docs/user-guide/src/capm3/automated_cleaning.md
  docs/user-guide/src/capm3/introduction.md
  docs/user-guide/src/capm3/node_reuse.md
  docs/user-guide/src/developer_environment/tryit.md
  docs/user-guide/src/introduction.md
  docs/user-guide/src/ironic/ironic_variables.md
  hack/markdownlint.sh
  processes/triage.md
Labels: approved, size/XL, lgtm

#379 add spellchecker, and fix pre-existing issues
  .cspell-config.json
  design/fd-support-kcp.md
  design/ironic_authentication.md
  design/metadata-handling.md
  design/physical-network-api-prototype.md
  design/reproducible-metal3-dev-env.md
  design/sync-labels-bmh-to-node.md
  design/use-ironic.md
  hack/shellcheck.sh
  hack/spellcheck.sh
  processes/triage.md
Labels: size/L, approved, lgtm
