Repository metal3-io/metal3-docs, pull requests merged in 2025-01, with the labels that each got.

#492 Mention redfish-virtual media in live-iso example
  docs/user-guide/src/bmo/live-iso.md
Labels: size/XS, approved, lgtm

#496 update versions in support table
  docs/user-guide/src/version_support.md
Labels: size/XS, approved, lgtm

#493 User guide: first take at documenting IrSO
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/irso/install-basics.md
  docs/user-guide/src/irso/introduction.md
Labels: size/L, approved, lgtm

#498 fix cncf sandbox proposal dead link
  design/community/foundation-proposal.md
Labels: size/XS, approved, lgtm

#499 remove obsolete crs_reference.md
  crs_reference.md
  images/v1a2_crs.drawio
  images/v1a2_crs.png
  images/v1a2_crs.svg
Labels: approved, lgtm, size/M

#502 Update command to create userdata
  docs/user-guide/src/bmo/instance_customization.md
Labels: size/XS, approved, lgtm

#500 remove space from "architectural diagrams" dir name
  images/architectural_diagrams/cluster_api.svg
  images/architectural_diagrams/components.svg
  images/architectural_diagrams/ipam.svg
  images/architectural_diagrams/object_representation.svg
Labels: size/XS, approved, lgtm
