Repository metal3-io/metal3-docs, pull requests merged in 2025-06, with the labels that each got.

#527 Remove additional slash
  docs/user-guide/src/developer_environment/tryit.md
Labels: size/XS, approved, lgtm, ok-to-test

#546 Fix broken link in troubleshooting.md
  docs/user-guide/src/troubleshooting.md
Labels: size/XS, approved, lgtm, ok-to-test

#542 Fix broken github links at annotation-for-power-cycling-and-deleting-failed-nodes.md
  design/baremetal-operator/annotation-for-power-cycling-and-deleting-failed-nodes.md
Labels: size/XS, approved, lgtm, ok-to-test

#548 add dependabot config for workflows
  .github/dependabot.yml
Labels: approved, size/S, lgtm

#537 Set IRONIC_EXTERNAL_IP for virtualized environment
  docs/user-guide/src/quick-start.md
Labels: size/XS, approved, lgtm, ok-to-test

#544 Fix broken link in processes/reviewer-permissions-migration.md
  processes/reviewer-permissions-migration.md
Labels: approved, size/S, lgtm, ok-to-test

#549 User guide: link to IrSO rendered API reference
  docs/user-guide/src/irso/install-basics.md
  docs/user-guide/src/irso/introduction.md
Labels: approved, size/S, lgtm

#550 update releasing process doc
  .cspell-config.json
  processes/releasing.md
Labels: approved, lgtm, size/M

#539 fix the broken link from CAPI
  docs/user-guide/src/capm3/pivoting.md
Labels: size/XS, approved, lgtm, ok-to-test
