Repository metal3-io/metal3-docs, pull requests merged in 2025-04, with the labels that each got.

#509 Refresh the BMH v1beta1 design based on recent developments
  design/baremetal-operator/bmh-v1beta1.md
Labels: approved, lgtm, size/M

#512 Update versions for ironic-image and IrSO
  docs/user-guide/src/irso/introduction.md
  docs/user-guide/src/version_support.md
Labels: approved, size/S, lgtm

#497 Modifying notes on checksum to reflect recent updates regarding empty checksumType field
  docs/user-guide/src/bmo/provisioning.md
Labels: size/XS, approved, lgtm, ok-to-test

#511 Troubleshooting: add another common issue related to forced deletion
  docs/user-guide/src/troubleshooting.md
Labels: size/XS, approved, lgtm

#515 Updating IPClaim section for optional annotation
  docs/user-guide/src/ipam/introduction.md
Labels: size/XS, approved, lgtm, ok-to-test
