Repository metal3-io/metal3-docs, pull requests merged in 2025-02, with the labels that each got.

#503 Update MariaDB release docs
  processes/releasing.md
Labels: approved, size/S, lgtm

#504 Correct BareMetalHost example in Advanced Instance Customization
  docs/user-guide/src/bmo/advanced_instance_customization.md
Labels: size/XS, approved, lgtm, ok-to-test

#506 Update ironic-image supported matrix for v28.0
  docs/user-guide/src/version_support.md
Labels: approved, size/S, lgtm

#507 Update IrSO matrix for ironic-image 28.0
  docs/user-guide/src/irso/introduction.md
Labels: size/XS, approved, lgtm
