Repository metal3-io/metal3-docs, pull requests merged in 2025-05, with the labels that each got.

#514 Dev env documentation updates
  docs/user-guide/src/developer_environment/tryit.md
Labels: approved, size/S, lgtm, ok-to-test

#505 :seedling: Add broken link check action
  .github/workflows/pr-link-check.yml
  .github/workflows/scheduled-link-check.yml
  .lycheeignore
  docs/user-guide/src/capm3/features.md
Labels: approved, lgtm, size/M

#521 Give upstream as a argument to workflow call
  .github/workflows/pr-link-check.yml
Labels: size/XS, approved, lgtm

#519 User guide: document database support for IrSO
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/irso/database.md
  docs/user-guide/src/irso/install-basics.md
Labels: size/L, approved, lgtm

#525 User guide: document the current state of ExternallyProvisioned
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/externally_provisioned.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/images/provisioning-states.dot
  docs/user-guide/src/bmo/images/provisioning-states.png
  docs/user-guide/src/bmo/state_machine.md
Labels: approved, lgtm, size/M

#516 :seedling: Update version support tables release-1.10
  docs/user-guide/src/version_support.md
Labels: approved, lgtm, size/M

#526 User guide: retitle BMO features to explain what they do
  docs/user-guide/src/SUMMARY.md
  docs/user-guide/src/bmo/detached_annotation.md
  docs/user-guide/src/bmo/features.md
  docs/user-guide/src/bmo/inspect_annotation.md
  docs/user-guide/src/bmo/live-iso.md
  docs/user-guide/src/bmo/reboot_annotation.md
  docs/user-guide/src/bmo/root_device_hints.md
  docs/user-guide/src/bmo/status_annotation.md
Labels: approved, lgtm, size/M
